version: '2'

# when sharing the host folder, you need to reinstall Ruby gems
# and npm modules into the vendor folder

services:
  assets:
    env_file:
      - .env
    image: datacite/sitemaps
    ports:
      - "9080:4567"
    volumes:
      - .:/home/app/webapp
